export const gutenbergCatalog = [
  {
    title: 'Pride and Prejudice',
    author: 'Austen, Jane',
    gutenbergId: 1342,
    minReadHours: 4,
    synopsis: 'Pride and Prejudice is a romance classic about courtship and domestic fiction. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Romance","Classic Literature"],
  },
  {
    title: 'Moby Dick; Or, The Whale',
    author: 'Melville, Herman',
    gutenbergId: 2701,
    minReadHours: 4,
    synopsis: 'Moby Dick; Or, The Whale is a adventure classic about adventure stories and ahab, captain (fictitious character). Drawn from Adventure shelves. A widely read public-domain favorite.',
    tags: ["Adventure","Classic Literature"],
  },
  {
    title: 'Frankenstein; or, the modern prometheus',
    author: 'Shelley, Mary Wollstonecraft',
    gutenbergId: 84,
    minReadHours: 4,
    synopsis: 'Frankenstein; or, the modern prometheus is a science fiction classic about frankenstein\'s monster (fictitious character) and frankenstein, victor (fictitious character). Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Science Fiction","Fantasy","Horror","Gothic","Classic Literature"],
  },
  {
    title: 'Dracula',
    author: 'Stoker, Bram',
    gutenbergId: 345,
    minReadHours: 4,
    synopsis: 'Dracula is a fantasy classic about dracula, count (fictitious character) and epistolary fiction. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Fantasy","Horror","Gothic","Mystery","Classic Literature"],
  },
  {
    title: 'The Picture of Dorian Gray',
    author: 'Wilde, Oscar',
    gutenbergId: 174,
    minReadHours: 4,
    synopsis: 'The Picture of Dorian Gray is a gothic classic about appearance (philosophy) and conduct of life. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Gothic","Philosophy","History","Classic Literature"],
  },
  {
    title: 'The Time Machine',
    author: 'Wells, H. G. (Herbert George)',
    gutenbergId: 35,
    minReadHours: 4,
    synopsis: 'The Time Machine is a science fiction classic about dystopias and science fiction. Drawn from British Literature shelves. A public-domain edition for calm reading.',
    tags: ["Science Fiction","Fantasy","Travel","Classic Literature"],
  },
  {
    title: 'The war of the worlds',
    author: 'Wells, H. G. (Herbert George)',
    gutenbergId: 36,
    minReadHours: 4,
    synopsis: 'The war of the worlds is a science fiction classic about imaginary wars and battles and life on other planets. Drawn from British Literature shelves. A public-domain edition for calm reading.',
    tags: ["Science Fiction","Fantasy","War","Classic Literature"],
  },
  {
    title: 'Alice\'s Adventures in Wonderland',
    author: 'Carroll, Lewis',
    gutenbergId: 11,
    minReadHours: 4,
    synopsis: 'Alice\'s Adventures in Wonderland is a fantasy classic about alice (fictitious character from carroll) and children\'s stories. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Fantasy","Children's","Classic Literature"],
  },
  {
    title: 'The Adventures of Sherlock Holmes',
    author: 'Doyle, Arthur Conan',
    gutenbergId: 1661,
    minReadHours: 4,
    synopsis: 'The Adventures of Sherlock Holmes is a mystery classic about detective and mystery stories, english and holmes, sherlock (fictitious character). Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Mystery","Detective","Short Stories","Classic Literature"],
  },
  {
    title: 'The call of the wild',
    author: 'London, Jack',
    gutenbergId: 215,
    minReadHours: 4,
    synopsis: 'The call of the wild is a adventure classic about adventure stories and animal welfare. Drawn from Adventure shelves. A public-domain edition for calm reading.',
    tags: ["Adventure","Nature","Classic Literature"],
  },
  {
    title: 'A Tale of Two Cities',
    author: 'Dickens, Charles',
    gutenbergId: 98,
    minReadHours: 4,
    synopsis: 'A Tale of Two Cities is a history classic about british -- france -- paris and executions and executioners. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["History","Historical Fiction","War","Classic Literature"],
  },
  {
    title: 'Great Expectations',
    author: 'Dickens, Charles',
    gutenbergId: 1400,
    minReadHours: 4,
    synopsis: 'Great Expectations is a literary fiction classic about benefactors and bildungsromans. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Literary Fiction","Classic Literature"],
  },
  {
    title: 'The Odyssey: Rendered into English prose for the use of those who cannot read the original',
    author: 'Homer',
    gutenbergId: 1727,
    minReadHours: 4,
    synopsis: 'The Odyssey: Rendered into English prose for the use of those who cannot read the original is a poetry classic about epic poetry, greek -- translations into english and homer -- translations into english. Drawn from Classics of Literature shelves. A widely read public-domain favorite.',
    tags: ["Poetry","Mythology","Classic Literature"],
  },
  {
    title: 'The Iliad',
    author: 'Homer',
    gutenbergId: 6130,
    minReadHours: 4,
    synopsis: 'The Iliad is a poetry classic about achilles (mythological character) -- poetry and classical literature. Drawn from Classics of Literature shelves. A public-domain edition for calm reading.',
    tags: ["Poetry","Mythology","War","Classic Literature"],
  },
  {
    title: 'The Art of War',
    author: 'Sunzi, active 6th century B.C.',
    gutenbergId: 132,
    minReadHours: 4,
    synopsis: 'The Art of War is a history classic about military art and science -- early works to 1800 and war -- early works to 1800. Drawn from History - Ancient shelves. A public-domain edition for calm reading.',
    tags: ["History","War","Classic Literature"],
  },
  {
    title: 'A Christmas Carol in Prose; Being a Ghost Story of Christmas',
    author: 'Dickens, Charles',
    gutenbergId: 46,
    minReadHours: 4,
    synopsis: 'A Christmas Carol in Prose; Being a Ghost Story of Christmas is a children\'s classic about christmas stories and ghost stories. Drawn from British Literature shelves. A public-domain edition for calm reading.',
    tags: ["Children's","Classic Literature"],
  },
  {
    title: 'A Cyclopaedia of Canadian Biography: Being Chiefly Men of the Time: A Collection of Persons Distinguished in Professional and Political Life, Leaders in the Commerce and Industry of Canada, and Successful Pioneers',
    author: 'Unknown',
    gutenbergId: 57724,
    minReadHours: 4,
    synopsis: 'A Cyclopaedia of Canadian Biography: Being Chiefly Men of the Time: A Collection of Persons Distinguished in Professional and Political Life, Leaders in the Commerce and Industry of Canada, and Successful Pioneers is a history classic about canada -- biography and canada -- biography -- dictionaries. Drawn from Biographies shelves. A public-domain edition for calm reading.',
    tags: ["History","Classic Literature"],
  },
  {
    title: 'A Doll\'s House : a play',
    author: 'Ibsen, Henrik',
    gutenbergId: 2542,
    minReadHours: 4,
    synopsis: 'A Doll\'s House : a play is a drama classic about man-woman relationships -- drama and marriage -- drama. Drawn from Classics of Literature shelves. A widely read public-domain favorite.',
    tags: ["Drama","Classic Literature"],
  },
  {
    title: 'A Modest Proposal: For preventing the children of poor people in Ireland, from being a burden on their parents or country, and for making them beneficial to the publick',
    author: 'Swift, Jonathan',
    gutenbergId: 1080,
    minReadHours: 4,
    synopsis: 'A Modest Proposal: For preventing the children of poor people in Ireland, from being a burden on their parents or country, and for making them beneficial to the publick is a humor classic about ireland -- politics and government -- 18th century -- humor and political satire, english. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Humor","Politics","Essays","Classic Literature"],
  },
  {
    title: 'A Room with a View',
    author: 'Forster, E. M. (Edward Morgan)',
    gutenbergId: 2641,
    minReadHours: 4,
    synopsis: 'A Room with a View is a romance classic about british -- italy and england. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Romance","Classic Literature"],
  },
  {
    title: 'A Source Book for Ancient Church History',
    author: 'Ayer, Joseph Cullen',
    gutenbergId: 24979,
    minReadHours: 4,
    synopsis: 'A Source Book for Ancient Church History is a history classic with enduring themes and vivid storytelling. Drawn from History - Ancient shelves. A public-domain edition for calm reading.',
    tags: ["History","Classic Literature"],
  },
  {
    title: 'A Study in Scarlet',
    author: 'Doyle, Arthur Conan',
    gutenbergId: 244,
    minReadHours: 4,
    synopsis: 'A Study in Scarlet is a mystery classic about detective and mystery stories and england. Drawn from British Literature shelves. A public-domain edition for calm reading.',
    tags: ["Mystery","Detective","Classic Literature"],
  },
  {
    title: 'Adventures of Huckleberry Finn',
    author: 'Twain, Mark',
    gutenbergId: 76,
    minReadHours: 4,
    synopsis: 'Adventures of Huckleberry Finn is a adventure classic about adventure stories and bildungsromans. Drawn from Adventure shelves. A widely read public-domain favorite.',
    tags: ["Adventure","Children's","Classic Literature"],
  },
  {
    title: 'An Inquiry into the Nature and Causes of the Wealth of Nations',
    author: 'Smith, Adam',
    gutenbergId: 3300,
    minReadHours: 4,
    synopsis: 'An Inquiry into the Nature and Causes of the Wealth of Nations is a economics classic about economics. Drawn from Economics shelves. A public-domain edition for calm reading.',
    tags: ["Economics","History","Classic Literature"],
  },
  {
    title: 'Anna Karenina',
    author: 'Tolstoy, Leo, graf',
    gutenbergId: 1399,
    minReadHours: 4,
    synopsis: 'Anna Karenina is a literary fiction classic about adultery and didactic fiction. Drawn from Classics of Literature shelves. A public-domain edition for calm reading.',
    tags: ["Literary Fiction","Classic Literature"],
  },
  {
    title: 'Anne of Green Gables',
    author: 'Montgomery, L. M. (Lucy Maud)',
    gutenbergId: 45,
    minReadHours: 4,
    synopsis: 'Anne of Green Gables is a children\'s classic about bildungsromans and canada -- history -- 1867-1914. Drawn from Children & Young Adult Reading shelves. A widely read public-domain favorite.',
    tags: ["Children's","History","Classic Literature"],
  },
  {
    title: 'Autobiography of Benjamin Franklin',
    author: 'Franklin, Benjamin',
    gutenbergId: 20203,
    minReadHours: 4,
    synopsis: 'Autobiography of Benjamin Franklin is a history classic about franklin, benjamin, 1706-1790 and statesmen -- united states -- biography. Drawn from American Literature shelves. A public-domain edition for calm reading.',
    tags: ["History","Classic Literature"],
  },
  {
    title: 'Belford\'s Magazine, Vol 2, December 1888',
    author: 'Various',
    gutenbergId: 32105,
    minReadHours: 4,
    synopsis: 'Belford\'s Magazine, Vol 2, December 1888 is a poetry classic about united states -- politics and government -- periodicals. Drawn from Journals shelves. A public-domain edition for calm reading.',
    tags: ["Poetry","Short Stories","Politics","Classic Literature"],
  },
  {
    title: 'Beowulf: An Anglo-Saxon Epic Poem',
    author: 'Unknown',
    gutenbergId: 16328,
    minReadHours: 4,
    synopsis: 'Beowulf: An Anglo-Saxon Epic Poem is a poetry classic about dragons -- poetry and epic poetry, english (old). Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Poetry","Mythology","Classic Literature"],
  },
  {
    title: 'Beyond Good and Evil',
    author: 'Nietzsche, Friedrich Wilhelm',
    gutenbergId: 4363,
    minReadHours: 4,
    synopsis: 'Beyond Good and Evil is a philosophy classic about ethics and philosophy, german. Drawn from Philosophy & Ethics shelves. A public-domain edition for calm reading.',
    tags: ["Philosophy","Classic Literature"],
  },
  {
    title: 'Bleak House',
    author: 'Dickens, Charles',
    gutenbergId: 1023,
    minReadHours: 4,
    synopsis: 'Bleak House is a children\'s classic about bildungsromans and domestic fiction. Drawn from British Literature shelves. A public-domain edition for calm reading.',
    tags: ["Children's","Classic Literature"],
  },
  {
    title: 'Calculus Made Easy: Being a very-simplest introduction to those beautiful methods which are generally called by the terrifying names of the Differential Calculus and the Integral Calculus',
    author: 'Thompson, Silvanus P. (Silvanus Phillips)',
    gutenbergId: 33283,
    minReadHours: 4,
    synopsis: 'Calculus Made Easy: Being a very-simplest introduction to those beautiful methods which are generally called by the terrifying names of the Differential Calculus and the Integral Calculus is a nonfiction classic about calculus. Drawn from Mathematics shelves. A public-domain edition for calm reading.',
    tags: ["Nonfiction","Classic Literature"],
  },
  {
    title: 'Chambers\'s Twentieth Century Dictionary (part 1 of 4: A-D)',
    author: 'Unknown',
    gutenbergId: 37683,
    minReadHours: 4,
    synopsis: 'Chambers\'s Twentieth Century Dictionary (part 1 of 4: A-D) is a nonfiction classic about english language -- dictionaries. Drawn from Encyclopedias/Dictionaries/Reference shelves. A public-domain edition for calm reading.',
    tags: ["Nonfiction","Classic Literature"],
  },
  {
    title: 'Concrete Construction: Methods and Costs',
    author: 'Gillette, Halbert Powers',
    gutenbergId: 24855,
    minReadHours: 4,
    synopsis: 'Concrete Construction: Methods and Costs is a nonfiction classic about concrete construction. Drawn from Engineering & Technology shelves. A public-domain edition for calm reading.',
    tags: ["Nonfiction","Classic Literature"],
  },
  {
    title: 'Cranford',
    author: 'Gaskell, Elizabeth Cleghorn',
    gutenbergId: 394,
    minReadHours: 4,
    synopsis: 'Cranford is a literary fiction classic about england and female friendship. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Literary Fiction","Classic Literature"],
  },
  {
    title: 'Crime and Punishment',
    author: 'Dostoyevsky, Fyodor',
    gutenbergId: 2554,
    minReadHours: 4,
    synopsis: 'Crime and Punishment is a mystery classic about crime -- psychological aspects and detective and mystery stories. Drawn from Classics of Literature shelves. A widely read public-domain favorite.',
    tags: ["Mystery","Detective","Classic Literature"],
  },
  {
    title: 'Don Quixote',
    author: 'Cervantes Saavedra, Miguel de',
    gutenbergId: 996,
    minReadHours: 4,
    synopsis: 'Don Quixote is a literary fiction classic about knights and knighthood -- spain and picaresque literature. Drawn from Classics of Literature shelves. A public-domain edition for calm reading.',
    tags: ["Literary Fiction","Classic Literature"],
  },
  {
    title: 'Dr. Mabuse, der Spieler : $b Roman',
    author: 'Jacques, Norbert',
    gutenbergId: 50285,
    minReadHours: 4,
    synopsis: 'Dr. Mabuse, der Spieler : $b Roman is a mystery classic about criminals and gamblers. Drawn from Crime, Thrillers and Mystery shelves. A public-domain edition for calm reading.',
    tags: ["Mystery","Classic Literature"],
  },
  {
    title: 'Fifteen Thousand Useful Phrases',
    author: 'Kleiser, Grenville',
    gutenbergId: 26225,
    minReadHours: 4,
    synopsis: 'Fifteen Thousand Useful Phrases is a nonfiction classic about english language -- terms and phrases. A widely read public-domain favorite.',
    tags: ["Nonfiction","Classic Literature"],
  },
  {
    title: 'Frankenstein; Or, The Modern Prometheus',
    author: 'Shelley, Mary Wollstonecraft',
    gutenbergId: 42324,
    minReadHours: 4,
    synopsis: 'Frankenstein; Or, The Modern Prometheus is a science fiction classic about frankenstein\'s monster (fictitious character) and frankenstein, victor (fictitious character). Drawn from British Literature shelves. A public-domain edition for calm reading.',
    tags: ["Science Fiction","Fantasy","Horror","Gothic","Classic Literature"],
  },
  {
    title: 'Frankenstein; Or, The Modern Prometheus',
    author: 'Shelley, Mary Wollstonecraft',
    gutenbergId: 41445,
    minReadHours: 4,
    synopsis: 'Frankenstein; Or, The Modern Prometheus is a science fiction classic about frankenstein\'s monster (fictitious character) and frankenstein, victor (fictitious character). Drawn from British Literature shelves. A public-domain edition for calm reading.',
    tags: ["Science Fiction","Fantasy","Horror","Gothic","Classic Literature"],
  },
  {
    title: 'Grimms\' Fairy Tales',
    author: 'Grimm, Jacob',
    gutenbergId: 2591,
    minReadHours: 4,
    synopsis: 'Grimms\' Fairy Tales is a short stories classic about fairy tales -- germany. Drawn from Children & Young Adult Reading shelves. A widely read public-domain favorite.',
    tags: ["Short Stories","Children's","Mythology","Classic Literature"],
  },
  {
    title: 'Gulliver\'s Travels into Several Remote Nations of the World',
    author: 'Swift, Jonathan',
    gutenbergId: 829,
    minReadHours: 4,
    synopsis: 'Gulliver\'s Travels into Several Remote Nations of the World is a fantasy classic about fantasy fiction and gulliver, lemuel (fictitious character). Drawn from Adventure shelves. A public-domain edition for calm reading.',
    tags: ["Fantasy","Adventure","Classic Literature"],
  },
  {
    title: 'Heart of Darkness',
    author: 'Conrad, Joseph',
    gutenbergId: 219,
    minReadHours: 4,
    synopsis: 'Heart of Darkness is a literary fiction classic about africa and degeneration. Drawn from British Literature shelves. A public-domain edition for calm reading.',
    tags: ["Literary Fiction","Classic Literature"],
  },
  {
    title: 'History of Tom Jones, a Foundling',
    author: 'Fielding, Henry',
    gutenbergId: 6593,
    minReadHours: 4,
    synopsis: 'History of Tom Jones, a Foundling is a psychology classic about bildungsromans and england. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Psychology","Classic Literature"],
  },
  {
    title: 'Jane Eyre: An Autobiography',
    author: 'Brontë, Charlotte',
    gutenbergId: 1260,
    minReadHours: 4,
    synopsis: 'Jane Eyre: An Autobiography is a romance classic about bildungsromans and charity-schools. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Romance","Classic Literature"],
  },
  {
    title: 'Les mille et une nuits, tome premier',
    author: 'Unknown',
    gutenbergId: 26296,
    minReadHours: 4,
    synopsis: 'Les mille et une nuits, tome premier is a nonfiction classic about fairy tales and tales -- arab countries. A public-domain edition for calm reading.',
    tags: ["Nonfiction","Classic Literature"],
  },
  {
    title: 'Les Misérables',
    author: 'Hugo, Victor',
    gutenbergId: 135,
    minReadHours: 4,
    synopsis: 'Les Misérables is a historical fiction classic about epic literature and ex-convicts. Drawn from Classics of Literature shelves. A public-domain edition for calm reading.',
    tags: ["Historical Fiction","Classic Literature"],
  },
  {
    title: 'Leviathan',
    author: 'Hobbes, Thomas',
    gutenbergId: 3207,
    minReadHours: 4,
    synopsis: 'Leviathan is a philosophy classic about political science -- early works to 1800 and state, the -- early works to 1800. Drawn from History - Early Modern (c. 1450-1750) shelves. A widely read public-domain favorite.',
    tags: ["Philosophy","Politics","History","Classic Literature"],
  },
  {
    title: 'Little Women; Or, Meg, Jo, Beth, and Amy',
    author: 'Alcott, Louisa May',
    gutenbergId: 37106,
    minReadHours: 4,
    synopsis: 'Little Women; Or, Meg, Jo, Beth, and Amy is a children\'s classic about autobiographical fiction and bildungsromans. Drawn from American Literature shelves. A widely read public-domain favorite.',
    tags: ["Children's","Classic Literature"],
  },
  {
    title: 'Manual of Military Training: Second, Revised Edition',
    author: 'Moss, James A. (James Alfred)',
    gutenbergId: 26706,
    minReadHours: 4,
    synopsis: 'Manual of Military Training: Second, Revised Edition is a history classic about united states. army -- handbooks, manuals, etc.. Drawn from History - Warfare shelves. A public-domain edition for calm reading.',
    tags: ["History","Classic Literature"],
  },
  {
    title: 'Meditations',
    author: 'Marcus Aurelius, Emperor of Rome',
    gutenbergId: 2680,
    minReadHours: 4,
    synopsis: 'Meditations is a philosophy classic about ethics and stoics. Drawn from Biographies shelves. A widely read public-domain favorite.',
    tags: ["Philosophy","Classic Literature"],
  },
  {
    title: 'Metamorphosis',
    author: 'Kafka, Franz',
    gutenbergId: 5200,
    minReadHours: 4,
    synopsis: 'Metamorphosis is a horror classic about metamorphosis and psychological fiction. Drawn from Classics of Literature shelves. A widely read public-domain favorite.',
    tags: ["Horror","Classic Literature"],
  },
  {
    title: 'Middlemarch',
    author: 'Eliot, George',
    gutenbergId: 145,
    minReadHours: 4,
    synopsis: 'Middlemarch is a historical fiction classic about bildungsromans and city and town life. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Historical Fiction","Classic Literature"],
  },
  {
    title: 'Moby Multiple Language Lists of Common Words',
    author: 'Ward, Grady',
    gutenbergId: 3206,
    minReadHours: 4,
    synopsis: 'Moby Multiple Language Lists of Common Words is a nonfiction classic about words and phrase lists -- english. Drawn from Encyclopedias/Dictionaries/Reference shelves. A widely read public-domain favorite.',
    tags: ["Nonfiction","Classic Literature"],
  },
  {
    title: 'My Life — Volume 1',
    author: 'Wagner, Richard',
    gutenbergId: 5197,
    minReadHours: 4,
    synopsis: 'My Life — Volume 1 is a nonfiction classic about composers -- germany -- biography and wagner, richard, 1813-1883. Drawn from Biographies shelves. A widely read public-domain favorite.',
    tags: ["Nonfiction","Classic Literature"],
  },
  {
    title: 'Narrative of the Life of Frederick Douglass, an American Slave',
    author: 'Douglass, Frederick',
    gutenbergId: 23,
    minReadHours: 4,
    synopsis: 'Narrative of the Life of Frederick Douglass, an American Slave is a history classic about abolitionists -- united states -- biography and african american abolitionists -- biography. Drawn from Biographies shelves. A widely read public-domain favorite.',
    tags: ["History","Classic Literature"],
  },
  {
    title: 'Noli Me Tangere',
    author: 'Rizal, José',
    gutenbergId: 20228,
    minReadHours: 4,
    synopsis: 'Noli Me Tangere is a history classic about historical fiction and philippines -- history -- 1812-1898. Drawn from Novels shelves. A widely read public-domain favorite.',
    tags: ["History","Historical Fiction","Classic Literature"],
  },
  {
    title: 'Notes from the Underground',
    author: 'Dostoyevsky, Fyodor',
    gutenbergId: 600,
    minReadHours: 4,
    synopsis: 'Notes from the Underground is a politics classic about political fiction and russia -- history -- 1801-1917. Drawn from Novels shelves. A public-domain edition for calm reading.',
    tags: ["Politics","History","Classic Literature"],
  },
  {
    title: 'Oedipus King of Thebes: Translated into English Rhyming Verse with Explanatory Notes',
    author: 'Sophocles',
    gutenbergId: 27673,
    minReadHours: 4,
    synopsis: 'Oedipus King of Thebes: Translated into English Rhyming Verse with Explanatory Notes is a drama classic about oedipus (greek mythological figure) -- drama and tragedies (drama). Drawn from Classics of Literature shelves. A widely read public-domain favorite.',
    tags: ["Drama","Mythology","Classic Literature"],
  },
  {
    title: 'Oliver Twist',
    author: 'Dickens, Charles',
    gutenbergId: 730,
    minReadHours: 4,
    synopsis: 'Oliver Twist is a literary fiction classic about bildungsromans and criminals. Drawn from British Literature shelves. A public-domain edition for calm reading.',
    tags: ["Literary Fiction","Classic Literature"],
  },
  {
    title: 'Peter Pan : $b [Peter and Wendy]',
    author: 'Barrie, J. M. (James Matthew)',
    gutenbergId: 16,
    minReadHours: 4,
    synopsis: 'Peter Pan : $b [Peter and Wendy] is a fantasy classic about fairies and fantasy literature. Drawn from Adventure shelves. A public-domain edition for calm reading.',
    tags: ["Fantasy","Adventure","Children's","Classic Literature"],
  },
  {
    title: 'Romeo and Juliet',
    author: 'Shakespeare, William',
    gutenbergId: 1513,
    minReadHours: 4,
    synopsis: 'Romeo and Juliet is a romance classic about conflict of generations -- drama and juliet (fictitious character) -- drama. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Romance","Drama","Classic Literature"],
  },
  {
    title: 'Second Treatise of Government',
    author: 'Locke, John',
    gutenbergId: 7370,
    minReadHours: 4,
    synopsis: 'Second Treatise of Government is a philosophy classic about liberty -- early works to 1800 and political science -- early works to 1800. Drawn from History - Early Modern (c. 1450-1750) shelves. A widely read public-domain favorite.',
    tags: ["Philosophy","Politics","History","Classic Literature"],
  },
  {
    title: 'Sense and Sensibility',
    author: 'Austen, Jane',
    gutenbergId: 161,
    minReadHours: 4,
    synopsis: 'Sense and Sensibility is a romance classic about domestic fiction and england. Drawn from British Literature shelves. A public-domain edition for calm reading.',
    tags: ["Romance","Classic Literature"],
  },
  {
    title: 'Simple Sabotage Field Manual',
    author: 'United States. Office of Strategic Services',
    gutenbergId: 26184,
    minReadHours: 4,
    synopsis: 'Simple Sabotage Field Manual is a history classic about sabotage. Drawn from History - Modern (1750+) shelves. A widely read public-domain favorite.',
    tags: ["History","Classic Literature"],
  },
  {
    title: 'Spoon River Anthology',
    author: 'Masters, Edgar Lee',
    gutenbergId: 26471,
    minReadHours: 4,
    synopsis: 'Spoon River Anthology is a poetry classic about american poetry. A widely read public-domain favorite.',
    tags: ["Poetry","Classic Literature"],
  },
  {
    title: 'The Adventures of Ferdinand Count Fathom — Complete',
    author: 'Smollett, T. (Tobias)',
    gutenbergId: 6761,
    minReadHours: 4,
    synopsis: 'The Adventures of Ferdinand Count Fathom — Complete is a gothic classic about adventure stories and gothic fiction. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Gothic","Adventure","Classic Literature"],
  },
  {
    title: 'The Adventures of Roderick Random',
    author: 'Smollett, T. (Tobias)',
    gutenbergId: 4085,
    minReadHours: 4,
    synopsis: 'The Adventures of Roderick Random is a historical fiction classic about england and impressment. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Historical Fiction","Classic Literature"],
  },
  {
    title: 'The Adventures of Tom Sawyer, Complete',
    author: 'Twain, Mark',
    gutenbergId: 74,
    minReadHours: 4,
    synopsis: 'The Adventures of Tom Sawyer, Complete is a adventure classic about adventure stories and bildungsromans. Drawn from Adventure shelves. A widely read public-domain favorite.',
    tags: ["Adventure","Children's","Classic Literature"],
  },
  {
    title: 'The Blue Castle: a novel',
    author: 'Montgomery, L. M. (Lucy Maud)',
    gutenbergId: 67979,
    minReadHours: 4,
    synopsis: 'The Blue Castle: a novel is a romance classic about canada -- history -- 1914-1945 and choice (psychology). Drawn from Novels shelves. A widely read public-domain favorite.',
    tags: ["Romance","Psychology","History","Classic Literature"],
  },
  {
    title: 'The Brothers Karamazov',
    author: 'Dostoyevsky, Fyodor',
    gutenbergId: 28054,
    minReadHours: 4,
    synopsis: 'The Brothers Karamazov is a literary fiction classic about brothers and didactic fiction. Drawn from Classics of Literature shelves. A widely read public-domain favorite.',
    tags: ["Literary Fiction","Classic Literature"],
  },
  {
    title: 'The City of God, Volume I',
    author: 'Augustine, of Hippo, Saint',
    gutenbergId: 45304,
    minReadHours: 4,
    synopsis: 'The City of God, Volume I is a philosophy classic about apologetics -- early works to 1800 and kingdom of god -- early works to 1800. Drawn from History - Ancient shelves. A public-domain edition for calm reading.',
    tags: ["Philosophy","Religion","Spirituality","History","Classic Literature"],
  },
  {
    title: 'The Complete Works of William Shakespeare',
    author: 'Shakespeare, William',
    gutenbergId: 100,
    minReadHours: 4,
    synopsis: 'The Complete Works of William Shakespeare is a poetry classic about english drama -- early modern and elizabethan, 1500-1600. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Poetry","Drama","Classic Literature"],
  },
  {
    title: 'The Confessions of St. Augustine',
    author: 'Augustine, of Hippo, Saint',
    gutenbergId: 3296,
    minReadHours: 4,
    synopsis: 'The Confessions of St. Augustine is a philosophy classic about augustine, of hippo, saint, 354-430 and bishops -- algeria -- hippo (extinct city) -- biography. Drawn from Biographies shelves. A widely read public-domain favorite.',
    tags: ["Philosophy","Religion","Spirituality","Classic Literature"],
  },
  {
    title: 'The Count of Monte Cristo',
    author: 'Dumas, Alexandre',
    gutenbergId: 1184,
    minReadHours: 4,
    synopsis: 'The Count of Monte Cristo is a adventure classic about adventure stories and dantès, edmond (fictitious character). Drawn from Adventure shelves. A widely read public-domain favorite.',
    tags: ["Adventure","History","Historical Fiction","Classic Literature"],
  },
  {
    title: 'The divine comedy',
    author: 'Dante Alighieri',
    gutenbergId: 8800,
    minReadHours: 4,
    synopsis: 'The divine comedy is a poetry classic about epic poetry, italian -- translations into english and italian poetry -- to 1400 -- translations into english. Drawn from Classics of Literature shelves. A public-domain edition for calm reading.',
    tags: ["Poetry","Classic Literature"],
  },
  {
    title: 'The Enchanted April',
    author: 'Von Arnim, Elizabeth',
    gutenbergId: 16389,
    minReadHours: 4,
    synopsis: 'The Enchanted April is a literary fiction classic about british -- italy and domestic fiction. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Literary Fiction","Classic Literature"],
  },
  {
    title: 'The Expedition of Humphry Clinker',
    author: 'Smollett, T. (Tobias)',
    gutenbergId: 2160,
    minReadHours: 4,
    synopsis: 'The Expedition of Humphry Clinker is a humor classic about epistolary fiction and great britain. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Humor","Historical Fiction","Travel","Essays","Classic Literature"],
  },
  {
    title: 'The Federalist Papers',
    author: 'Hamilton, Alexander',
    gutenbergId: 22788,
    minReadHours: 4,
    synopsis: 'The Federalist Papers is a history classic about constitutional history -- united states -- sources and constitutional law -- united states. Drawn from United States shelves. A public-domain edition for calm reading.',
    tags: ["History","Classic Literature"],
  },
  {
    title: 'The Great Gatsby',
    author: 'Fitzgerald, F. Scott (Francis Scott)',
    gutenbergId: 64317,
    minReadHours: 4,
    synopsis: 'The Great Gatsby is a literary fiction classic about first loves and long island (n.y.). Drawn from American Literature shelves. A widely read public-domain favorite.',
    tags: ["Literary Fiction","Classic Literature"],
  },
  {
    title: 'The Hound of the Baskervilles',
    author: 'Doyle, Arthur Conan',
    gutenbergId: 2852,
    minReadHours: 4,
    synopsis: 'The Hound of the Baskervilles is a mystery classic about blessing and cursing and dartmoor (england). Drawn from British Literature shelves. A public-domain edition for calm reading.',
    tags: ["Mystery","Detective","Classic Literature"],
  },
  {
    title: 'The Importance of Being Earnest: A Trivial Comedy for Serious People',
    author: 'Wilde, Oscar',
    gutenbergId: 844,
    minReadHours: 4,
    synopsis: 'The Importance of Being Earnest: A Trivial Comedy for Serious People is a drama classic about comedy plays and england -- drama. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Drama","Psychology","Classic Literature"],
  },
  {
    title: 'The Interesting Narrative of the Life of Olaudah Equiano, Or Gustavus Vassa, The African: Written By Himself',
    author: 'Equiano, Olaudah',
    gutenbergId: 15399,
    minReadHours: 4,
    synopsis: 'The Interesting Narrative of the Life of Olaudah Equiano, Or Gustavus Vassa, The African: Written By Himself is a history classic about enslaved persons -- great britain -- biography and enslaved persons -- united states -- biography. Drawn from Biographies shelves. A public-domain edition for calm reading.',
    tags: ["History","Classic Literature"],
  },
  {
    title: 'The Itching Palm: A Study of the Habit of Tipping in America',
    author: 'Scott, William R. (William Rufus)',
    gutenbergId: 33170,
    minReadHours: 4,
    synopsis: 'The Itching Palm: A Study of the Habit of Tipping in America is a philosophy classic about tipping. Drawn from American Literature shelves. A public-domain edition for calm reading.',
    tags: ["Philosophy","Economics","Classic Literature"],
  },
  {
    title: 'The Junior Classics, Volume 1: Fairy and wonder tales',
    author: 'Neilson, William Allan',
    gutenbergId: 28942,
    minReadHours: 4,
    synopsis: 'The Junior Classics, Volume 1: Fairy and wonder tales is a children\'s classic about children\'s literature. A public-domain edition for calm reading.',
    tags: ["Children's","Classic Literature"],
  },
  {
    title: 'The King in Yellow',
    author: 'Chambers, Robert W. (Robert William)',
    gutenbergId: 8492,
    minReadHours: 4,
    synopsis: 'The King in Yellow is a fantasy classic about horror tales, american and short stories, american. Drawn from American Literature shelves. A widely read public-domain favorite.',
    tags: ["Fantasy","Horror","Mystery","Short Stories","Classic Literature"],
  },
  {
    title: 'The King James Version of the Bible',
    author: 'Unknown',
    gutenbergId: 10,
    minReadHours: 4,
    synopsis: 'The King James Version of the Bible is a religion classic with enduring themes and vivid storytelling. Drawn from Classics of Literature shelves. A public-domain edition for calm reading.',
    tags: ["Religion","Spirituality","Classic Literature"],
  },
  {
    title: 'The Legend of Sleepy Hollow',
    author: 'Irving, Washington',
    gutenbergId: 41,
    minReadHours: 4,
    synopsis: 'The Legend of Sleepy Hollow is a short stories classic about ghosts and new york (state) -- history -- 1775-1865. Drawn from American Literature shelves. A public-domain edition for calm reading.',
    tags: ["Short Stories","Children's","Mythology","History","Classic Literature"],
  },
  {
    title: 'The lesser Key of Solomon, Goetia, the book of evil spirits : $b contains two hundred diagrams and seals for invocation and convocation of spirits, necromancy, witchcraft and black art',
    author: 'Unknown',
    gutenbergId: 72679,
    minReadHours: 4,
    synopsis: 'The lesser Key of Solomon, Goetia, the book of evil spirits : $b contains two hundred diagrams and seals for invocation and convocation of spirits, necromancy, witchcraft and black art is a religion classic about occultism. Drawn from Religion/Spirituality shelves. A public-domain edition for calm reading.',
    tags: ["Religion","Spirituality","Classic Literature"],
  },
  {
    title: 'The Mayflower, January, 1905',
    author: 'Various',
    gutenbergId: 29951,
    minReadHours: 4,
    synopsis: 'The Mayflower, January, 1905 is a nature classic about gardening -- periodicals and horticulture -- periodicals. Drawn from How To ... shelves. A public-domain edition for calm reading.',
    tags: ["Nature","Classic Literature"],
  },
  {
    title: 'The Outline of History: Being a Plain History of Life and Mankind',
    author: 'Wells, H. G. (Herbert George)',
    gutenbergId: 45368,
    minReadHours: 4,
    synopsis: 'The Outline of History: Being a Plain History of Life and Mankind is a history classic about world history. Drawn from History - Other shelves. A public-domain edition for calm reading.',
    tags: ["History","Classic Literature"],
  },
  {
    title: 'The Outline of Science, Vol. 1 (of 4): A Plain Story Simply Told',
    author: 'Thomson, J. Arthur (John Arthur)',
    gutenbergId: 20417,
    minReadHours: 4,
    synopsis: 'The Outline of Science, Vol. 1 (of 4): A Plain Story Simply Told is a nonfiction classic about science. Drawn from Science - Biology shelves. A public-domain edition for calm reading.',
    tags: ["Nonfiction","Classic Literature"],
  },
  {
    title: 'The Prince',
    author: 'Machiavelli, Niccolò',
    gutenbergId: 1232,
    minReadHours: 4,
    synopsis: 'The Prince is a philosophy classic about political ethics -- early works to 1800 and political science -- philosophy -- early works to 1800. Drawn from History - Early Modern (c. 1450-1750) shelves. A widely read public-domain favorite.',
    tags: ["Philosophy","Politics","History","Classic Literature"],
  },
  {
    title: 'The Republic',
    author: 'Plato',
    gutenbergId: 1497,
    minReadHours: 4,
    synopsis: 'The Republic is a philosophy classic about classical literature and justice -- early works to 1800. Drawn from Classics of Literature shelves. A widely read public-domain favorite.',
    tags: ["Philosophy","Politics","Classic Literature"],
  },
  {
    title: 'The Romance of Lust: A classic Victorian erotic novel',
    author: 'Anonymous',
    gutenbergId: 30254,
    minReadHours: 4,
    synopsis: 'The Romance of Lust: A classic Victorian erotic novel is a literary fiction classic about corporal punishment and erotic fiction. Drawn from Sexuality & Erotica shelves. A public-domain edition for calm reading.',
    tags: ["Literary Fiction","Classic Literature"],
  },
  {
    title: 'The Scarlet Letter',
    author: 'Hawthorne, Nathaniel',
    gutenbergId: 25344,
    minReadHours: 4,
    synopsis: 'The Scarlet Letter is a children\'s classic about adultery and boston (mass.) -- history -- colonial period, ca. 1600-1775. Drawn from American Literature shelves. A widely read public-domain favorite.',
    tags: ["Children's","History","Historical Fiction","Classic Literature"],
  },
  {
    title: 'The scrap book, Volume 2, No. 2',
    author: 'Various',
    gutenbergId: 72075,
    minReadHours: 4,
    synopsis: 'The scrap book, Volume 2, No. 2 is a essays classic about periodicals. Drawn from Essays, Letters & Speeches shelves. A public-domain edition for calm reading.',
    tags: ["Essays","Classic Literature"],
  },
  {
    title: 'The Souls of Black Folk',
    author: 'Du Bois, W. E. B. (William Edward Burghardt)',
    gutenbergId: 408,
    minReadHours: 4,
    synopsis: 'The Souls of Black Folk is a politics classic about african americans. Drawn from Essays, Letters & Speeches shelves. A widely read public-domain favorite.',
    tags: ["Politics","History","Essays","Classic Literature"],
  },
  {
    title: 'The Turn of the Screw',
    author: 'James, Henry',
    gutenbergId: 209,
    minReadHours: 4,
    synopsis: 'The Turn of the Screw is a horror classic about children and england. Drawn from British Literature shelves. A public-domain edition for calm reading.',
    tags: ["Horror","Gothic","Mystery","Children's","Classic Literature"],
  },
  {
    title: 'The Wonderful Wizard of Oz',
    author: 'Baum, L. Frank (Lyman Frank)',
    gutenbergId: 55,
    minReadHours: 4,
    synopsis: 'The Wonderful Wizard of Oz is a fantasy classic about courage and cowardly lion (fictitious character). Drawn from Adventure shelves. A widely read public-domain favorite.',
    tags: ["Fantasy","Adventure","Children's","Classic Literature"],
  },
  {
    title: 'The writings of Clement of Alexandria, Vol. 1 (of 2)',
    author: 'Clement, of Alexandria, Saint',
    gutenbergId: 71937,
    minReadHours: 4,
    synopsis: 'The writings of Clement of Alexandria, Vol. 1 (of 2) is a philosophy classic about theology -- early works to 1800 and theology -- history -- early church, ca. 30-600. Drawn from History - Religious shelves. A public-domain edition for calm reading.',
    tags: ["Philosophy","Religion","Spirituality","History","Classic Literature"],
  },
  {
    title: 'The Yellow Wallpaper',
    author: 'Gilman, Charlotte Perkins',
    gutenbergId: 1952,
    minReadHours: 4,
    synopsis: 'The Yellow Wallpaper is a gothic classic about feminist fiction and married women -- psychology. Drawn from American Literature shelves. A widely read public-domain favorite.',
    tags: ["Gothic","Short Stories","Psychology","Classic Literature"],
  },
  {
    title: 'Three Hundred Tang Poems, Volume 1',
    author: 'Various',
    gutenbergId: 20968,
    minReadHours: 4,
    synopsis: 'Three Hundred Tang Poems, Volume 1 is a poetry classic about chinese poetry -- tang dynasty, 618-907. A public-domain edition for calm reading.',
    tags: ["Poetry","Classic Literature"],
  },
  {
    title: 'Thus Spake Zarathustra: A Book for All and None',
    author: 'Nietzsche, Friedrich Wilhelm',
    gutenbergId: 1998,
    minReadHours: 4,
    synopsis: 'Thus Spake Zarathustra: A Book for All and None is a philosophy classic about philosophy, german and superman (philosophical concept). Drawn from Classics of Literature shelves. A widely read public-domain favorite.',
    tags: ["Philosophy","Classic Literature"],
  },
  {
    title: 'Tractatus Logico-Philosophicus',
    author: 'Wittgenstein, Ludwig',
    gutenbergId: 5740,
    minReadHours: 4,
    synopsis: 'Tractatus Logico-Philosophicus is a philosophy classic about language and languages -- philosophy and logic, symbolic and mathematical. Drawn from DE Sachbuch shelves. A public-domain edition for calm reading.',
    tags: ["Philosophy","Classic Literature"],
  },
  {
    title: 'Treasure Island',
    author: 'Stevenson, Robert Louis',
    gutenbergId: 120,
    minReadHours: 4,
    synopsis: 'Treasure Island is a adventure classic about pirates and sea stories. Drawn from Adventure shelves. A widely read public-domain favorite.',
    tags: ["Adventure","Children's","Historical Fiction","Classic Literature"],
  },
  {
    title: 'Twenty years after',
    author: 'Dumas, Alexandre',
    gutenbergId: 1259,
    minReadHours: 4,
    synopsis: 'Twenty years after is a adventure classic about france -- history -- louis xiv, 1643-1715. Drawn from Adventure shelves. A widely read public-domain favorite.',
    tags: ["Adventure","History","Historical Fiction","Classic Literature"],
  },
  {
    title: 'Ulysses',
    author: 'Joyce, James',
    gutenbergId: 4300,
    minReadHours: 4,
    synopsis: 'Ulysses is a psychology classic about alienation (social psychology) and artists. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Psychology","Classic Literature"],
  },
  {
    title: 'Walden, and On The Duty Of Civil Disobedience',
    author: 'Thoreau, Henry David',
    gutenbergId: 205,
    minReadHours: 4,
    synopsis: 'Walden, and On The Duty Of Civil Disobedience is a philosophy classic about authors, american -- 19th century -- biography and civil disobedience. Drawn from American Literature shelves. A widely read public-domain favorite.',
    tags: ["Philosophy","History","Essays","Classic Literature"],
  },
  {
    title: 'War and Peace',
    author: 'Tolstoy, Leo, graf',
    gutenbergId: 2600,
    minReadHours: 4,
    synopsis: 'War and Peace is a history classic about aristocracy (social class) -- russia and historical fiction. Drawn from Classics of Literature shelves. A widely read public-domain favorite.',
    tags: ["History","Historical Fiction","War","Classic Literature"],
  },
  {
    title: 'White nights, and other stories',
    author: 'Dostoyevsky, Fyodor',
    gutenbergId: 36034,
    minReadHours: 4,
    synopsis: 'White nights, and other stories is a short stories classic about dostoyevsky, fyodor, 1821-1881 -- translations into english and russian fiction -- translations into english. Drawn from Russian Literature shelves. A widely read public-domain favorite.',
    tags: ["Short Stories","Classic Literature"],
  },
  {
    title: 'Wuthering Heights',
    author: 'Brontë, Emily',
    gutenbergId: 768,
    minReadHours: 4,
    synopsis: 'Wuthering Heights is a gothic classic about domestic fiction and foundlings. Drawn from British Literature shelves. A widely read public-domain favorite.',
    tags: ["Gothic","Psychology","Classic Literature"],
  },
  {
    title: '西遊記',
    author: 'Wu, Cheng\'en',
    gutenbergId: 23962,
    minReadHours: 4,
    synopsis: '西遊記 is a fantasy classic about chinese fiction -- ming dynasty, 1368-1644 and folklore -- china. Drawn from Adventure shelves. A public-domain edition for calm reading.',
    tags: ["Fantasy","Adventure","Mythology","Classic Literature"],
  },
  {
    title: '警世通言',
    author: 'Feng, Menglong',
    gutenbergId: 24141,
    minReadHours: 4,
    synopsis: '警世通言 is a short stories classic about chinese fiction -- ming dynasty, 1368-1644 and short stories, chinese. Drawn from Mythology, Legends & Folklore shelves. A widely read public-domain favorite.',
    tags: ["Short Stories","Mythology","Classic Literature"],
  },
];
